language: python
sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
      update: true
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
install:
  - pip install -r requirements.txt -U
  - pip install -r requirements_test.txt -U
before_script:
  - export DJANGO_SETTINGS_MODULE=kono_data.settings
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py makemigrations --dry-run
  - python manage.py migrate
  - coverage run manage.py test
after_success:
  - coverage report --omit=/home/
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  - nvm install 10.16.0
  - npm install -g ionic
  - cd kono-data-frontend
  - npm install
  - ionic build --prod -- --base-href /static/ionic/
  - rm -rf ../data_model/static/ionic/
  - mkdir ../data_model/static/ionic/
  - cp -rf www/* ../data_model/static/ionic/
  - cd ..
  - zappa update prod
  - zappa manage prod migrate
  - zappa manage prod "collectstatic --noinput"
