language: python
sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
install:
  - pip install -r requirements.txt -U
  - pip install -r requirements_test.txt -U
before_script:
  - export DJANGO_SETTINGS_MODULE=kono_data.settings
  - psql -c 'create database travis_ci_test;' -U postgres
  - cat config/database.yml.travis
script:
  - python manage.py makemigrations --dry-run
  - python manage.py migrate
  - coverage run manage.py test
after_success:
  - coverage report