# Generated by Django 2.0.4 on 2018-04-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_uri',
            field=models.CharField(help_text='Give Amazon Resource Name (ARN), e.g.: "arn:aws:s3:::test-kono-data"', max_length=128),
        ),
    ]
