# Generated by Django 2.0.4 on 2018-05-01 09:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Keys in your dataset, will be automatically fetched and overwritten each time you save.', null=True),
        ),
    ]
