# Generated by Django 2.0.4 on 2018-04-25 22:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='possible_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=1000),
        ),
    ]
