# Generated by Django 2.0.4 on 2018-05-06 06:03

import data_model.enums
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_auto_20180501_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Keys in your dataset, will be automatically fetched and overwritten each time you save.'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source_region',
            field=models.CharField(choices=[('ap-south-1', 'ap-south-1'), ('ap-northeast-1', 'ap-northeast-1'), ('ap-northeast-2', 'ap-northeast-2'), ('ap-northeast-3', 'ap-northeast-3'), ('ap-southeast-1', 'ap-southeast-1'), ('ap-southeast-2', 'ap-southeast-2'), ('cn-north-1', 'cn-north-1'), ('cn-northwest-1', 'cn-northwest-1'), ('eu-central-1', 'eu-central-1'), ('eu-west-1', 'eu-west-1'), ('eu-west-2', 'eu-west-2'), ('eu-west-3', 'eu-west-3'), ('sa-east-1', 'sa-east-1'), ('us-east-1', 'us-east-1'), ('us-east-2', 'us-east-2'), ('us-west-1', 'us-west-1'), ('us-west-2', 'us-west-2'), ('ca-central-1', 'ca-central-1')], default=data_model.enums.AwsRegionType('eu-west-1'), help_text='Give the AWS region of the S3 bucket. Required to show the content', max_length=16),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='source_uri',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='label',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
