# Generated by Django 2.0.4 on 2018-04-30 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0002_auto_20180430_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor_datasets', to=settings.AUTH_USER_MODEL),
        ),
    ]
