# Generated by Django 2.0.4 on 2018-04-25 22:45

import data_model.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0005_auto_20180425_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_region',
            field=models.CharField(choices=[('eu_central_1', 'eu-central-1'), ('eu_west_1', 'eu-west-1')], default=data_model.enums.AwsRegionType('eu-west-1'), max_length=16),
        ),
    ]
