# Generated by Django 2.0.4 on 2018-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='key',
            field=models.CharField(max_length=128),
        ),
    ]
