# Generated by Django 2.0.4 on 2018-05-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0008_dataset_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='key',
            new_name='task',
        ),
    ]
