# Generated by Django 2.0.4 on 2018-05-19 10:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0010_auto_20180516_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
    ]
