# Generated by Django 2.0.4 on 2018-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0011_auto_20180519_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='action',
            field=models.CharField(choices=[('solve', 'solve'), ('skip', 'skip')], default='solve', max_length=64),
            preserve_default=False,
        ),
    ]
