# Generated by Django 2.1 on 2018-08-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0014_dataset_invite_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='processing_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
