# Generated by Django 2.1 on 2018-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0015_label_processing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='loading_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
