# Generated by Django 2.1.7 on 2019-03-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('data_model', '0019_auto_20190324_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='task_external',
        ),
        migrations.AddField(
            model_name='task',
            name='dataset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='tasks', to='data_model.Dataset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels',
                                    to='data_model.Task'),
        ),
    ]
