# Generated by Django 2.2.4 on 2020-07-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model', '0020_auto_20190324_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='data_model.Dataset'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('dataset', 'definition'), name='Task with definition per dataset must be unique constraint'),
        ),
    ]
